name: CI

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        include:
          - {os: ubuntu-latest,  als-pattern: 'als-*-linux-x64.tar.gz',    als-location: 'integration/vscode/ada/x64/linux', emacs-version: 'snapshot'}
    runs-on: ${{matrix.os}}

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install Texinfo (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt --assume-yes install texinfo

      - name: Install Texinfo (Windows)
        if: runner.os == 'Windows'
        uses: msys2/setup-msys2@v2
        with:
          install: texinfo

      - name: Install Texinfo (MacOS)
        if: runner.os == 'macOS'
        run: brew install texinfo

      # See https://lists.gnu.org/archive/html/emacs-devel/2021-09/msg00521.html
      - name: Fix MSYS2 makeinfo Installation (Windows)
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          echo @echo off>> ${{runner.temp}}\msys64\mingw64\bin\makeinfo.bat
          echo ${{runner.temp}}\msys64\usr\bin\perl ${{runner.temp}}\msys64\usr\bin\makeinfo %%*>> ${{runner.temp}}\msys64\mingw64\bin\makeinfo.bat
          echo ${{runner.temp}}\msys64\mingw64\bin>> %GITHUB_PATH%

      - name: Install Ada Languager Server (Windows)
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          gh release download --repo AdaCore/ada_language_server --pattern ${{matrix.als-pattern}} --output ${{runner.temp}}\als.tar.gz
          if not exist ${{runner.temp}}\als mkdir ${{runner.temp}}\als
          tar -xzvf ${{runner.temp}}\als.tar.gz --directory ${{runner.temp}}\als
          echo ${{runner.temp}}\als\${{matrix.als-location}}>> %GITHUB_PATH%
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Install Ada Language Server (Linux, MacOS)
        if: runner.os != 'Windows'
        run: |
          gh release download --repo AdaCore/ada_language_server --pattern ${{matrix.als-pattern}} --output ${{runner.temp}}/als.tar.gz
          mkdir -p ${{runner.temp}}/als
          tar -xzvf ${{runner.temp}}/als.tar.gz --directory ${{runner.temp}}/als
          echo "${{runner.temp}}/als/${{matrix.als-location}}" >> $GITHUB_PATH
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Display ALS Version
        run: ada_language_server --version

      - name: Install a recent GNAT/GPRbuild
        uses: alire-project/setup-alire@latest
        with:
          toolchain: gnat_native^14 gprbuild

      - name: Add Compiler to PATH
        run: |
          echo ~/.local/share/alire/toolchains/gnat_native*/bin >> $GITHUB_PATH
          echo ~/.local/share/alire/toolchains/gprbuild*/bin >> $GITHUB_PATH

      - name: Display Compiler Version
        run: gnatls -v

      - name: Setup Emacs
        uses: jcs090218/setup-emacs@master
        with:
          version: ${{matrix.emacs-version}}

      - name: Setup Eldev
        uses: emacs-eldev/setup-eldev@v1.5

      - name: Test the project
        run: eldev test eglot-als-other-file-2
